concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  BINARY_PATH: brut.apktool/apktool-lib/src/main/resources/prebuilt
jobs:
  analyze-linux-aapt:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Verify Executable
      run: ${{ env.BINARY_PATH }}/linux/${{ matrix.file }} version
    - continue-on-error: true
      name: Output Static
      run: ldd ${{ env.BINARY_PATH }}/linux/${{ matrix.file }} || true
    strategy:
      matrix:
        file:
        - aapt
        - aapt_64
        - aapt2
        - aapt2_64
  analyze-mac-aapt:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Verify Executable
      run: ${{ env.BINARY_PATH }}/macosx/${{ matrix.file }} version
    - continue-on-error: true
      name: Output Static
      run: otool -L ${{ env.BINARY_PATH }}/macosx/${{ matrix.file }} || true
    strategy:
      matrix:
        file:
        - aapt_64
        - aapt2_64
  analyze-windows-aapt:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Verify Executable
      run: ${{ env.BINARY_PATH }}/windows/${{ matrix.file }} version
    - continue-on-error: true
      name: Output Static
      run: ldd ${{ env.BINARY_PATH }}/windows/${{ matrix.file }} || true
    strategy:
      matrix:
        file:
        - aapt.exe
        - aapt_64.exe
        - aapt2.exe
        - aapt2_64.exe
  build-and-test-with-Java-8-and-later:
    name: Build/Test (JDK ${{ matrix.java }}, ${{ matrix.os }})
    needs:
    - analyze-mac-aapt
    - analyze-linux-aapt
    - analyze-windows-aapt
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3.3.2
    - continue-on-error: true
      if: runner.os != 'Windows'
      name: Build (Linux/Mac)
      run: ./gradlew build shadowJar proguard
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: Build (Windows)
      run: ./gradlew.bat build shadowJar proguard
    strategy:
      fail-fast: true
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
  upload-artifact:
    if: github.repository == 'iBotPeaches/Apktool' && github.ref == 'refs/heads/master'
    name: Build apktool.jar
    needs:
    - build-and-test-with-Java-8-and-later
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        dependency-graph: generate-and-submit
    - continue-on-error: true
      if: runner.os != 'Windows'
      name: Build (Linux/Mac)
      run: ./gradlew build shadowJar proguard
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: Build (Windows)
      run: ./gradlew.bat build shadowJar proguard
    - continue-on-error: true
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: apktool.jar
        path: brut.apktool/apktool-cli/build/libs/apktool-v*
name: CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
