concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  validate-gradle-wrapper:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@v3.3.2
name: Gradle Validate
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
